### ISSUE TITLE
Views in the Strong Testimonials plugin have not been copied.

### ISSUE THREAD

**Issue by alican532** [wpmudev/blogtemplates#1]
Hi, I've tried the new version of beta. He made a mistake. Views in the Strong Testimonials plugin have not been copied.

Also, the reset-change-template does not work after the update.
(Https://premium.wpmudev.org/forums/topic/prosites-integration-with-blog-templates)
For the reset-change-template, please see the end of the page.
[reset-change-template.zip](https://github.com/wpmudev/blogtemplates/files/3194502/reset-change-template.zip)

**Comment by alican532** [comment]
Also in the repair database section settings did not appear to me. 
Please improve this plugin. Wpmu giant plugins are very useful.
Thank you  :)

**Comment by Spoygg** [comment]
INACTIVE NOTICE: This plugin is unsupported by WPMUDEV, we've published it here for those technical types who might want to fork and maintain it for their needs.

Thank you for your interest, we have published these plugins on Github so that anyone can take them on if they want to continue development. We're open to merge pull requests if they are made.
